name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
    - name: Update Rust
      run: rustup update stable
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run cargo tests
      run: cargo test --locked
    - name: Check print-completions for bash
      run: cargo run --locked -- print-completions bash
    - name: Check print-completions for fish
      run: cargo run --locked -- print-completions fish
    - name: Check print-completions for zsh
      run: cargo run --locked -- print-completions zsh

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Update Rust
      run: rustup update stable
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run cargo format check
      run: cargo fmt -- --check
