name: Release

on:
  push:
    tags:
      - '*'

jobs:
  linux-bin:
    name: Build Linux musl binary
    runs-on: ubuntu-latest
    steps:
    - name: Update Rust stable toolchain
      run: rustup update stable
    - name: Add x86_64-unknown-linux-musl target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build release binary for Linux musl
      run: cargo build --release --locked --target=x86_64-unknown-linux-musl
    - name: Compress Linux musl binary
      run: tar c ab-av1 | zstd -T0 -19 > ab-av1-${{ github.ref_name }}-x86_64-unknown-linux-musl.tar.zst
      working-directory: target/x86_64-unknown-linux-musl/release/
    - name: Upload Linux musl binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/x86_64-unknown-linux-musl/release/ab-av1-${{ github.ref_name }}-x86_64-unknown-linux-musl.tar.zst
        tag: ${{ github.ref }}
        overwrite: true

  win-bin:
    name: Build Windows binary
    runs-on: windows-latest
    steps:
    - name: Update Rust stable toolchain
      run: rustup update stable
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build release binary for Windows
      run: cargo build --release --locked
    - name: Upload Windows binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/ab-av1.exe
        tag: ${{ github.ref }}
        overwrite: true
